import {test,expect,type Page} from '@playwright/test'
import {pauseAtStart} from './playback-helpers'
const add=async(page:Page,query:string,name:RegExp)=>{await page.getByRole('combobox',{name:'Search flights'}).fill(query);await page.getByRole('option',{name}).click()}
for(const renderer of ['canvas','three'])test(`${renderer}: country search highlights airports and combines flight filters`,async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto(`./?renderer=${renderer}`);await pauseAtStart(page)
 const all=await page.locator('.ms-study-timeline svg').innerHTML()
 await add(page,'Switzerland',/^Switzerland /)
 await expect(page.getByRole('button',{name:'Remove Switzerland'})).toBeVisible()
 await expect(page.locator('.country-summary')).toHaveText('13 airports highlighted · ')
 await expect(page.locator('.count')).toContainText('Switzerland')
 await expect.poll(()=>page.locator('.airport-map-label[data-country-highlighted=true]').count()).toBeGreaterThan(0)
 expect(await page.locator('.ms-study-timeline svg').innerHTML()).not.toEqual(all)
 await expect(page.getByRole('slider')).toHaveValue('25200')
 await add(page,'SWISS',/^SWISS /)
 await expect(page.locator('.count')).toContainText('SWISS')
 await add(page,'France',/^France /)
 await expect(page.locator('.country-summary')).toHaveText('148 airports highlighted · ')
 await page.getByRole('button',{name:'Remove Switzerland'}).click()
 await expect(page.locator('.country-summary')).toHaveText('135 airports highlighted · ')
 await page.getByRole('button',{name:'Clear all',exact:true}).click()
 await expect(page.locator('.country-summary')).toHaveCount(0)
 await expect(page.locator('.airport-map-label[data-country-highlighted=true]')).toHaveCount(0)
 expect(await page.locator('.ms-study-timeline svg').innerHTML()).toEqual(all)
 expect(errors).toEqual([])
})
test('country keyboard search, airport boards and empty-country selection remain usable on phones',async({page})=>{
 await page.setViewportSize({width:390,height:664});await page.goto('./');await pauseAtStart(page)
 const search=page.getByRole('combobox',{name:'Search flights'})
 await search.fill('CH');await search.press('Enter')
 await expect(page.getByRole('button',{name:'Remove Switzerland'})).toBeVisible()
 await add(page,'ZRH',/^ZRH Zurich/)
 await page.getByRole('button',{name:'ZRH board'}).click();await expect(page.locator('.airport-panel')).toBeVisible()
 await page.getByRole('button',{name:'Close airport board'}).click()
 await page.getByRole('button',{name:'Clear all',exact:true}).click()
 await add(page,'Liechtenstein',/^Liechtenstein /)
 await expect(page.locator('.country-summary')).toHaveText('0 airports highlighted · ')
 await expect(page.locator('.count')).toHaveText(/^0 aircraft/)
 await expect(page.locator('.play')).toBeInViewport()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})
