import {test,expect} from '@playwright/test'
import {pauseAtStart} from './playback-helpers'
test('evidence-aware continents, direction and candidate opt-in update the selection',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('./');await pauseAtStart(page)
 const initial=await page.locator('.ms-study-timeline svg').innerHTML()
 await page.getByRole('button',{name:'Destination and continent filters',exact:true}).click()
 const panel=page.getByRole('region',{name:'Destination and continent filters'})
 await expect(panel).toBeVisible()
 await expect(panel.locator('.endpoint-coverage')).toContainText('22,008 usable')
 await expect(panel.getByRole('checkbox',{name:'Include candidate-only labels'})).not.toBeChecked()
 await page.getByLabel('Endpoint continent',{exact:true}).selectOption('NA')
 await expect(page.locator('.selection-summary')).toContainText('4 aircraft')
 const filtered=await page.locator('.ms-study-timeline svg').innerHTML();expect(filtered).not.toEqual(initial)
 await panel.getByRole('checkbox',{name:'Include candidate-only labels'}).check()
 await expect(page.locator('.selection-summary')).not.toHaveText(/^4 aircraft/)
 await expect(page.locator('.ms-study-timeline__heading')).toContainText('candidates included')
 await panel.getByRole('checkbox',{name:'Include candidate-only labels'}).uncheck()
 await expect(page.locator('.selection-summary')).toContainText('4 aircraft')
 await page.getByLabel('Endpoint direction',{exact:true}).selectOption('origin')
 await expect(page.locator('.selection-summary')).toContainText('6 aircraft')
 await expect(panel.locator('.endpoint-coverage')).toContainText('22,508 usable')
 await page.getByRole('button',{name:'Reset endpoint filters'}).click()
 await page.getByRole('button',{name:'Close endpoint filters'}).click()
 expect(await page.locator('.ms-study-timeline svg').innerHTML()).toEqual(initial)
 expect(errors).toEqual([])
})
test('remote airport search, coverage, reset and phone layout remain usable',async({page})=>{
 await page.setViewportSize({width:390,height:664});await page.goto('./');await pauseAtStart(page)
 await page.getByRole('button',{name:'Destination and continent filters',exact:true}).click()
 const panel=page.getByRole('region',{name:'Destination and continent filters'})
 await page.getByLabel('Endpoint airport search').fill('PER')
 await panel.getByRole('button',{name:/^PER Perth/}).click()
 await expect(page.locator('.selection-summary')).toContainText('1 aircraft')
 await expect(page.locator('.ms-study-timeline__heading')).toContainText('To PER')
 await page.screenshot({path:`test-results/${test.info().project.name}-endpoint-filters.png`})
 await panel.getByRole('button',{name:'Reset endpoint filters'}).scrollIntoViewIfNeeded()
 await expect(page.locator('.play')).toBeInViewport()
 const rect=await panel.boundingBox(),footer=await page.locator('footer').boundingBox()
 expect(rect!.y+rect!.height).toBeLessThan(footer!.y)
 await panel.getByRole('button',{name:'Reset endpoint filters'}).click()
 await page.getByLabel('Endpoint continent',{exact:true}).selectOption('unresolved')
 await expect(page.locator('.selection-summary')).not.toContainText('0 aircraft')
 await page.getByRole('button',{name:'Close endpoint filters'}).click()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})
test('corrupt enrichment is rejected before filters are offered',async({page})=>{
 await page.route('**/enrichment/endpoints.json.gz.bin',route=>route.fulfill({body:'corrupt',contentType:'application/octet-stream'}))
 await page.goto('./');await expect(page.getByRole('status')).toContainText('Incomplete data download')
 await expect(page.getByRole('button',{name:'Destination and continent filters',exact:true})).toHaveCount(0)
})
test('endpoint search fits above a reduced phone keyboard viewport',async({page})=>{
 await page.setViewportSize({width:390,height:664});await page.goto('./');await pauseAtStart(page)
 await page.getByRole('button',{name:'Destination and continent filters',exact:true}).click()
 await page.evaluate(()=>{Object.defineProperty(window.visualViewport!,'height',{configurable:true,value:300});window.visualViewport!.dispatchEvent(new Event('resize'))})
 await page.getByLabel('Endpoint airport search').fill('PER')
 const panel=page.getByRole('region',{name:'Destination and continent filters'})
 const result=panel.getByRole('button',{name:/^PER Perth/});await result.scrollIntoViewIfNeeded()
 const box=await panel.boundingBox();expect(box!.y+box!.height).toBeLessThanOrEqual(289)
 await result.click();await expect(page.locator('.selection-summary')).toContainText('1 aircraft')
})
