import {test,expect} from '@playwright/test'
import {pauseAtStart} from './playback-helpers'
test('a selected flight distinguishes corroborated destination from observed origin',async({page})=>{
 await page.goto('./');await pauseAtStart(page)
 await page.getByRole('button',{name:'Destination and continent filters',exact:true}).click()
 await page.getByLabel('Endpoint airport search').fill('PER')
 await page.getByRole('region',{name:'Destination and continent filters'}).getByRole('button',{name:/^PER Perth/}).click()
 await page.getByRole('button',{name:'Close endpoint filters'}).click()
 await page.getByRole('combobox',{name:'Search flights'}).fill('LHR')
 await page.getByRole('option',{name:/^LHR London/}).click()
 await page.getByRole('slider').fill('45330')
 await page.getByRole('button',{name:'LHR board'}).click()
 await page.locator('.ms-split-flap-board__select').first().click()
 await expect(page.locator('.flight-caption')).toContainText('QFA10')
 await expect(page.locator('.endpoint-caption')).toContainText('LHR')
 await expect(page.locator('.endpoint-caption')).toContainText('Observed')
 await expect(page.locator('.endpoint-caption')).toContainText('PER')
 await expect(page.locator('.endpoint-caption')).toContainText('Corroborated')
 await page.getByRole('button',{name:'Close airport board'}).click()
 await page.getByRole('button',{name:'Clear all',exact:true}).click()
 await expect(page.locator('.selection-summary')).toHaveCount(0)
 await expect(page.getByRole('button',{name:'Destination and continent filters',exact:true})).not.toHaveAttribute('data-active','true')
})
