import {test,expect} from '@playwright/test'
import {pauseAtStart} from './playback-helpers'

test('insights toggles every category in the shared selection and survives collapse',async({page})=>{
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
 await page.goto('./');await pauseAtStart(page)
 const panel=page.getByRole('region',{name:'Insights',exact:true})
 const toggle=panel.getByRole('button',{name:/Insights Recorded day/})
 await expect(toggle).toHaveAttribute('aria-expanded','false');await toggle.click()
 const first=panel.locator('.insight-row').first()
 const carrier=await first.locator('strong').innerText()
 await first.click();await expect(page.getByRole('button',{name:`Remove ${carrier}`,exact:true})).toBeVisible()
 await expect(first).toHaveAttribute('aria-pressed','true')
 await first.click()
 await expect(page.getByRole('button',{name:`Remove ${carrier}`,exact:true})).toHaveCount(0)
 await expect(first).toHaveAttribute('aria-pressed','false')
 expect(new URL(page.url()).hash).toBe('')
 await first.press('Enter')
 await expect(first).toHaveAttribute('aria-pressed','true')
 const second=panel.locator('.insight-row').nth(1),other=await second.locator('strong').innerText()
 await second.click();await expect(page.getByRole('button',{name:`Remove ${other}`,exact:true})).toBeVisible()
 for(const category of ['Country','Continent','Airport']){
  await panel.getByRole('button',{name:category,exact:true}).click()
  const row=panel.locator('.insight-row').first(),label=await row.locator('strong').innerText()
  const previousHash=new URL(page.url()).hash
  await row.click();await expect(page.getByRole('button',{name:`Remove ${label}`,exact:true})).toBeVisible()
  await expect(page.locator('.ms-study-timeline__heading')).toContainText(label)
  await expect(row).toHaveAttribute('aria-pressed','true')
  await row.click()
  await expect(page.getByRole('button',{name:`Remove ${label}`,exact:true})).toHaveCount(0)
  await expect(row).toHaveAttribute('aria-pressed','false')
  expect(new URL(page.url()).hash).toBe(previousHash)
  await row.click()
 }
 await expect(page.getByRole('group',{name:'Selected filters'}).locator('.filter-pill')).toHaveCount(5)
 const bounds=await panel.boundingBox(),dock=await page.locator('footer').boundingBox()
 expect(bounds!.y+bounds!.height).toBeLessThan(dock!.y)
 await panel.locator('.insight-row').first().scrollIntoViewIfNeeded()
 const rowBounds=await panel.locator('.insight-row').first().boundingBox()
 expect(rowBounds!.y).toBeGreaterThanOrEqual(bounds!.y)
 expect(rowBounds!.y+rowBounds!.height).toBeLessThanOrEqual(bounds!.y+bounds!.height)
 await page.screenshot({path:`test-results/${test.info().project.name}-insights.png`,fullPage:true})
 await toggle.click();await expect(panel.locator('#insights-content')).toHaveCount(0)
 await expect(page.getByRole('group',{name:'Selected filters'}).locator('.filter-pill')).toHaveCount(5)
 await toggle.click();await expect(panel.getByRole('button',{name:'Airport',exact:true})).toHaveAttribute('aria-pressed','true')
 await page.getByRole('button',{name:'Clear all',exact:true}).click()
 await expect(page.getByRole('group',{name:'Selected filters'})).toHaveCount(0)
 await expect(page.locator('.count')).toContainText('over Europe')
 expect(errors).toEqual([])
})

test('country filters can be searched, removed, and insights can be operated by keyboard',async({page})=>{
 await page.goto('./');await pauseAtStart(page)
 const search=page.getByRole('combobox',{name:'Search flights'})
 await search.fill('Switzerland');await page.getByRole('option',{name:/^Switzerland/}).click()
 await expect(page.locator('.selection-summary')).toContainText('matching selection')
 const toggle=page.getByRole('button',{name:/Insights Recorded day/})
 await toggle.focus();await page.keyboard.press('Enter')
 const panel=page.getByRole('region',{name:'Insights',exact:true})
 await expect(panel.locator('.insight-row').first()).toBeVisible()
 await page.getByRole('button',{name:'Remove Switzerland',exact:true}).click()
 await expect(page.locator('.count')).toContainText('over Europe')
})
