import {test,expect} from '@playwright/test'

test('autoplay advances after loading and seeks preserve playing or paused state',async({page})=>{
 await page.goto('./')
 const play=page.locator('.play'),slider=page.getByRole('slider')
 const time=async()=>Number(await slider.inputValue())
 await expect(play).toHaveText('Pause');await expect(play).toBeEnabled()
 await expect.poll(time).toBeGreaterThan(25200)
 // A seek to a new chunk waits for data then continues without a Play click.
 await slider.fill('43200')
 await expect(play).toHaveText('Pause')
 await expect.poll(time).toBeGreaterThan(43200)
 await play.click();await expect(play).toHaveText('Play')
 await slider.fill('25200');await expect(slider).toHaveValue('25200')
 await slider.press('ArrowRight');await expect(slider).toHaveValue('25201')
 await page.waitForTimeout(250);await expect(slider).toHaveValue('25201')
 await expect(play).toHaveText('Play')
 await play.click()
 await slider.press('Home')
 await expect(play).toHaveText('Pause')
 await expect.poll(time).toBeLessThan(600)
 await expect.poll(time).toBeGreaterThan(0)
})

test('drag holds the chosen clock under the pointer and resumes only if already playing',async({page})=>{
 await page.goto('./');const play=page.locator('.play'),slider=page.getByRole('slider')
 await expect(play).toBeEnabled();await expect(play).toHaveText('Pause')
 const box=(await slider.boundingBox())!,x=box.x+box.width*.35,y=box.y+box.height/2
 await page.mouse.move(x,y);await page.mouse.down()
 await expect(page.locator('.stream-status')).toHaveText('Playing')
 await expect(play).toHaveText('Pause')
 const held=await slider.inputValue()
 await page.waitForTimeout(300);await expect(slider).toHaveValue(held)
 await page.mouse.move(box.x+box.width*.55,y,{steps:4})
 await expect(page.locator('.stream-status')).toHaveText('Playing')
 const target=Number(await slider.inputValue())
 await page.mouse.up();await expect(play).toHaveText('Pause')
 await expect.poll(async()=>Number(await slider.inputValue())).toBeGreaterThan(target)
 await play.click()
 await page.mouse.move(x,y);await page.mouse.down()
 await expect(page.locator('.stream-status')).toHaveText('Paused')
 const paused=await slider.inputValue();await page.mouse.up()
 await page.waitForTimeout(300);await expect(slider).toHaveValue(paused)
 await expect(play).toHaveText('Play')
})
