import {test,expect} from '@playwright/test'

test('renderer switches preserve clock, carrier and airport; GPU draws and falls back after context loss',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('./');await expect(page.getByRole('button',{name:'Play',exact:true})).toBeEnabled()
 await page.getByRole('combobox',{name:'Follow an airline'}).selectOption('swiss')
 await expect(page.locator('.airline-evidence')).toContainText('97 aircraft')
 await page.getByRole('combobox',{name:'Find an airport'}).fill('ZRH');await page.getByRole('combobox',{name:'Find an airport'}).press('Enter')
 await expect(page.locator('.count')).toHaveText(/^[1-9]\d* inbound.*SWISS/)
 const count=await page.locator('.count').innerText()
 const renderer=page.getByRole('combobox',{name:'Aircraft renderer'})
 await renderer.selectOption('three');await expect(renderer).toHaveValue('three');await expect(renderer).toBeEnabled()
 await expect(page.locator('.gpu-layer')).toHaveCount(1)
 await expect(page.getByRole('slider')).toHaveValue('25200')
 await expect(page.locator('.count')).toHaveText(count)
 await expect(page.locator('.ms-airport-hero')).toContainText('ZRH')
 await page.getByRole('button',{name:'Device details'}).click()
 await expect(page.locator('.diagnostics')).toContainText('Three.js')
 await expect(page.locator('.diagnostics')).toContainText(/[1-9]\d* GPU draw calls/)
 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async(text:string)=>{(window as any).__copiedResults=text}},configurable:true}))
 await page.getByRole('button',{name:'Copy results'}).click();await expect(page.locator('.diagnostics')).toContainText('Results copied')
 const copied=await page.evaluate(()=>JSON.parse((window as any).__copiedResults));expect(copied.renderer).toBe('three');expect(copied.release).toBe('0.2.2');expect(copied.gpu.calls).toBeGreaterThan(0);expect(copied.stagesP95Ms).toEqual(expect.objectContaining({sampling:expect.any(Number),geometry:expect.any(Number),submission:expect.any(Number)}));expect(copied.gpu.stateUploadBytes).toBeGreaterThan(0)
 await page.screenshot({path:`test-results/${test.info().project.name}-three.png`,fullPage:true})
 await page.getByRole('button',{name:'Reset measurements'}).click()
 await page.getByRole('button',{name:'Device details'}).click()
 await page.getByRole('combobox',{name:'Playback speed'}).selectOption('900')
 await page.getByRole('button',{name:'Play',exact:true}).click()
 await expect.poll(async()=>Number(await page.getByRole('slider').inputValue())).toBeGreaterThan(26400)
 await page.getByRole('button',{name:'Pause',exact:true}).click()
 await renderer.selectOption('canvas');await expect(page.locator('.gpu-layer')).toHaveCount(0)
 const time=await page.getByRole('slider').inputValue()
 await renderer.selectOption('three');await expect(page.locator('.gpu-layer')).toHaveCount(1);await expect(page.getByRole('slider')).toHaveValue(time)
 await page.locator('.gpu-layer').evaluate((canvas:HTMLCanvasElement)=>canvas.getContext('webgl2')!.getExtension('WEBGL_lose_context')!.loseContext())
 await expect(renderer).toHaveValue('canvas');await expect(page.locator('.gpu-layer')).toHaveCount(0)
 await expect(page.locator('.renderer-picker')).toContainText('context lost')
 await expect(page.getByRole('slider')).toHaveValue(time)
 expect(errors).toEqual([])
})
test('Three.js direct link works and density can return to moving aircraft',async({page})=>{
 await page.goto('./?renderer=three');await expect(page.getByRole('combobox',{name:'Aircraft renderer'})).toHaveValue('three')
 await expect(page.getByRole('button',{name:'Play',exact:true})).toBeEnabled()
 await page.getByRole('button',{name:'Hour density',exact:true}).click()
 await page.getByRole('slider').fill('43200');await expect(page.getByRole('slider')).toHaveValue('43200')
 await page.getByRole('button',{name:'Motion',exact:true}).click()
 await expect(page.locator('.count')).toHaveText(/^[1-9]\d*.*aircraft/)
 await expect(page.locator('.gpu-layer')).toHaveCount(1)
 await page.screenshot({path:`test-results/${test.info().project.name}-three-europe.png`,fullPage:true})
})
test('unavailable WebGL returns to the working Canvas renderer',async({page})=>{
 await page.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type:string,...args:any[]){if(type==='webgl2'||type==='webgl')return null;return Reflect.apply(original,this,[type,...args])} as typeof original})
 await page.goto('./?renderer=three')
 await expect(page.getByRole('button',{name:'Play',exact:true})).toBeEnabled()
 await expect(page.getByRole('combobox',{name:'Aircraft renderer'})).toHaveValue('canvas')
 await expect(page.locator('.renderer-picker')).toContainText('unavailable')
 await expect(page.locator('.count')).toContainText('aircraft')
 await expect(page.locator('.gpu-layer')).toHaveCount(0)
})
test('GPU playback loops at midnight without changing renderer or carrier',async({page})=>{
 await page.goto('./?renderer=three');await expect(page.getByRole('combobox',{name:'Aircraft renderer'})).toHaveValue('three')
 await expect(page.getByRole('button',{name:'Play',exact:true})).toBeEnabled()
 await page.getByRole('combobox',{name:'Follow an airline'}).selectOption('easyjet')
 await expect(page.locator('.airline-evidence')).toContainText('361 aircraft')
 await page.getByRole('slider').fill('86399');await expect(page.getByRole('slider')).toHaveValue('86399')
 await page.getByRole('combobox',{name:'Playback speed'}).selectOption('900')
 await page.getByRole('button',{name:'Play',exact:true}).click()
 await expect.poll(async()=>Number(await page.getByRole('slider').inputValue())).toBeLessThan(600)
 await expect(page.getByRole('combobox',{name:'Aircraft renderer'})).toHaveValue('three')
 await expect(page.getByRole('combobox',{name:'Follow an airline'})).toHaveValue('easyjet')
})
