import {test,expect} from '@playwright/test'
test('airport search, shared board, selected tracks, phone layout and fast streaming',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('./');await expect(page.getByRole('button',{name:'Play',exact:true})).toBeEnabled()
 await expect(page.locator('.count')).toContainText('aircraft')
 await page.getByRole('combobox',{name:'Find an airport'}).fill('Heathrow');await page.getByRole('combobox',{name:'Find an airport'}).press('Enter')
 await expect(page.locator('.ms-airport-hero')).toContainText('Heathrow')
 await expect(page.locator('.count')).toContainText('inbound');await expect(page.locator('.airport-key')).toContainText('Outbound')
 const rows=page.locator('.ms-split-flap-board__select');await expect(rows.first()).toBeVisible();await rows.first().click();await expect(page.locator('.flight-caption')).toBeVisible()
 await page.getByRole('button',{name:'Arrivals',exact:false}).click()
 await expect(page.locator('.ms-airport-hero')).toContainText('Arrivals')
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.waitForTimeout(1200);await page.screenshot({path:`test-results/${test.info().project.name}-airport.png`,fullPage:true})
 await page.getByRole('button',{name:'Hour density',exact:true}).click();await expect(page.locator('.count')).toContainText('Full study window');await expect(page.locator('.airport-key')).toHaveCount(0);await page.getByRole('button',{name:'Motion',exact:true}).click()
 await page.getByRole('button',{name:'Clear airport'}).click()
 await page.getByRole('slider',{name:'Time of day UTC'}).fill('28500')
 await page.getByRole('combobox',{name:'Playback speed'}).selectOption('900')
 await page.getByRole('button',{name:'Play',exact:true}).click()
 await page.waitForTimeout(5000)
 await expect(page.locator('.initial-loading')).toHaveCount(0)
 await expect.poll(async()=>Number(await page.getByRole('slider').inputValue())).toBeGreaterThan(29500)
 await page.getByRole('button',{name:'Pause',exact:true}).click()
 await page.getByRole('button',{name:'Device details'}).click()
 await expect(page.locator('.diagnostics')).toContainText('/ 4 chunks')
 await page.screenshot({path:`test-results/${test.info().project.name}-europe.png`,fullPage:true})
 expect(errors).toEqual([])
})
test('missing next chunk holds the last frame and offers a working retry',async({page})=>{
 await page.route('**/chunk-043.json.gz.bin',route=>route.fulfill({status:503,body:'unavailable'}))
 await page.goto('./');await expect(page.getByRole('button',{name:'Play',exact:true})).toBeEnabled()
 await page.getByRole('slider').fill('25795');await page.getByRole('combobox',{name:'Playback speed'}).selectOption('900');await page.getByRole('button',{name:'Play',exact:true}).click()
 await expect(page.locator('.stream-status')).toContainText('Retry');expect(Number(await page.getByRole('slider').inputValue())).toBeLessThan(25800)
 await expect(page.locator('.initial-loading')).toHaveCount(0)
 await page.unroute('**/chunk-043.json.gz.bin');await page.getByRole('button',{name:'Retry',exact:true}).click();await expect(page.locator('.stream-status')).toContainText('Paused')
 expect(Number(await page.getByRole('slider').inputValue())).toBeGreaterThanOrEqual(25800)
})

test('airline selection follows the map, airport board, activity and fast playback',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('./');await expect(page.getByRole('button',{name:'Play',exact:true})).toBeEnabled()
 const airline=page.getByRole('combobox',{name:'Follow an airline'})
 await expect.poll(async()=>Number((await page.locator('.count').innerText()).split(' ')[0].replaceAll(',',''))).toBeGreaterThan(100)
 const allCount=Number((await page.locator('.count').innerText()).split(' ')[0].replaceAll(',',''))
 const allActivity=await page.locator('.ms-study-timeline svg').innerHTML()
 await airline.selectOption('easyjet')
 await expect(page.locator('.count')).toHaveText(/^\d+ easyJet aircraft/)
 const easyCount=Number((await page.locator('.count').innerText()).split(' ')[0])
 expect(easyCount).toBeGreaterThan(0);expect(easyCount).toBeLessThan(allCount)
 await expect(page.locator('.airline-evidence')).toContainText('361 aircraft')
 await expect(page.locator('.ms-study-timeline__heading')).toContainText('easyJet')
 expect(await page.locator('.ms-study-timeline svg').innerHTML()).not.toEqual(allActivity)
 await page.getByRole('combobox',{name:'Find an airport'}).fill('LHR');await page.getByRole('combobox',{name:'Find an airport'}).press('Enter')
 await expect(page.locator('.association-note')).toContainText('0 outbound / 0 inbound associations for easyJet')
 await airline.selectOption('british-airways')
 await expect(page.locator('.ms-split-flap-board__select').first()).toBeVisible()
 await expect(page.locator('.ms-airport-hero')).toContainText('British Airways movements')
 await expect(page.getByRole('slider')).toHaveValue('25200')
 await page.getByRole('button',{name:'Clear airport'}).click()
 await airline.selectOption('swiss');await page.getByRole('combobox',{name:'Find an airport'}).fill('ZRH');await page.getByRole('combobox',{name:'Find an airport'}).press('Enter')
 await expect(page.locator('.ms-split-flap-board__select').first()).toBeVisible()
 await expect(page.locator('.ms-airport-hero')).toContainText('SWISS movements')
 await page.locator('.ms-split-flap-board__select').first().click()
 await expect(page.locator('.flight-caption strong')).toHaveText(/^SWR/)
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.waitForTimeout(1200)
 await page.screenshot({path:`test-results/${test.info().project.name}-swiss.png`,fullPage:true})
 await page.getByRole('button',{name:'Hour density',exact:true}).click()
 await expect(page.locator('.count')).toHaveText('SWISS · hourly observations')
 await page.getByRole('button',{name:'Motion',exact:true}).click()
 await page.getByRole('button',{name:'Clear airport'}).click()
 await airline.selectOption('easyjet')
 await page.getByRole('slider').fill('28500')
 await page.getByRole('combobox',{name:'Playback speed'}).selectOption('900')
 await page.getByRole('button',{name:'Play',exact:true}).click()
 await expect.poll(async()=>Number(await page.getByRole('slider').inputValue())).toBeGreaterThan(29500)
 await expect(page.locator('.count')).toHaveText(/^\d+ easyJet aircraft/)
 await expect(page.locator('.initial-loading')).toHaveCount(0)
 await page.getByRole('button',{name:'Pause',exact:true}).click()
 await page.screenshot({path:`test-results/${test.info().project.name}-easyjet.png`,fullPage:true})
 await airline.selectOption('all')
 await expect(page.locator('.airline-evidence')).toHaveCount(0)
 await expect(page.locator('.count')).not.toContainText('easyJet')
 expect(errors).toEqual([])
})

test('playback loops at midnight at slow and fast speeds, preserving the selection',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('./');await expect(page.getByRole('button',{name:'Play',exact:true})).toBeEnabled()
 await page.getByRole('combobox',{name:'Follow an airline'}).selectOption('swiss')
 await page.getByRole('combobox',{name:'Find an airport'}).fill('ZRH');await page.getByRole('combobox',{name:'Find an airport'}).press('Enter')
 for(const speed of ['60','900']){
  await page.getByRole('combobox',{name:'Playback speed'}).selectOption(speed)
  await page.getByRole('slider').fill('86399')
  await expect(page.locator('.stream-status')).toHaveText('Paused')
  await expect(page.getByRole('slider')).toHaveValue('86399')
  await page.getByRole('button',{name:'Play',exact:true}).click()
  await expect.poll(async()=>Number(await page.getByRole('slider').inputValue())).toBeLessThan(600)
  await expect(page.getByRole('button',{name:'Pause',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Pause',exact:true}).click()
  await expect(page.locator('.initial-loading')).toHaveCount(0)
  await expect(page.getByRole('combobox',{name:'Follow an airline'})).toHaveValue('swiss')
  await expect(page.getByRole('combobox',{name:'Playback speed'})).toHaveValue(speed)
  await expect(page.locator('.ms-airport-hero')).toContainText('ZRH')
  await expect(page.locator('.count')).toContainText('SWISS')
 }
 expect(errors).toEqual([])
})

test('expanded carrier data loads on demand, retries failures and ignores late selections',async({page})=>{
 const dataRequests:string[]=[]
 page.on('request',request=>{if(/\/generated\/airlines\/[^?]+\.json(?:\?|$)/.test(request.url())&&!request.url().includes('?import'))dataRequests.push(request.url())})
 await page.goto('./');await expect(page.getByRole('button',{name:'Play',exact:true})).toBeEnabled()
 const carrier=page.getByRole('combobox',{name:'Follow an airline'})
 await expect(carrier.locator('option')).toHaveCount(34)
 expect(dataRequests).toHaveLength(0)
 await carrier.selectOption('ryanair')
 await expect(page.locator('.ms-study-timeline__heading')).toContainText('Ryanair')
 await expect(page.locator('.airline-evidence')).toContainText('627 aircraft')
 expect(dataRequests.filter(url=>url.includes('/ryanair.json'))).toHaveLength(1)
 await carrier.selectOption('all');await carrier.selectOption('ryanair')
 await expect(page.locator('.ms-study-timeline__heading')).toContainText('Ryanair')
 expect(dataRequests.filter(url=>url.includes('/ryanair.json'))).toHaveLength(1)
 await page.route('**/generated/airlines/lufthansa.json',route=>route.fulfill({status:503,body:'unavailable'}))
 await carrier.selectOption('lufthansa')
 await expect(page.getByRole('alert')).toContainText('Select the airline again to retry')
 await expect(carrier).toHaveValue('ryanair')
 await expect(page.locator('.ms-study-timeline__heading')).toContainText('Ryanair')
 await page.unroute('**/generated/airlines/lufthansa.json')
 await carrier.selectOption('lufthansa')
 await expect(page.locator('.ms-study-timeline__heading')).toContainText('Lufthansa')
 await expect(page.getByRole('alert')).toHaveCount(0)
 let releaseDelay:()=>void=()=>{};const delayed=new Promise<void>(resolve=>{releaseDelay=resolve})
 await page.route('**/generated/airlines/klm.json',async route=>{await delayed;await route.continue()})
 await carrier.selectOption('klm');await expect(page.locator('.airline-loading')).toBeVisible()
 await expect(page.locator('.ms-study-timeline__heading')).toContainText('Lufthansa')
 await carrier.selectOption('all');releaseDelay()
 await expect.poll(()=>dataRequests.some(url=>url.includes('/klm.json'))).toBe(true)
 await expect(page.locator('.airline-loading')).toHaveCount(0)
 await page.waitForTimeout(300)
 await expect(carrier).toHaveValue('all')
 await expect(page.locator('.airline-evidence')).toHaveCount(0)
 await expect(page.locator('.ms-study-timeline__heading')).not.toContainText('KLM')
})

test('full map and shared timeline remain reachable while the airport panel scrolls',async({page})=>{
 await page.goto('./');await expect(page.getByRole('button',{name:'Play',exact:true})).toBeEnabled()
 const canvas=await page.locator('canvas').boundingBox(),viewport=page.viewportSize()!
 expect(canvas!.x).toBe(0);expect(canvas!.y).toBe(0)
 expect(canvas!.width).toBe(viewport.width);expect(canvas!.height).toBe(viewport.height)
 const slider=page.getByRole('slider',{name:'Time of day UTC'})
 await page.getByRole('button',{name:'Show activity as a line'}).click()
 await expect(page.locator('.ms-study-timeline svg polyline').first()).toBeVisible()
 await slider.focus();await slider.press('Home');await expect(slider).toHaveValue('0')
 await slider.fill('43200');await expect(slider).toHaveValue('43200')
 await page.getByRole('combobox',{name:'Find an airport'}).fill('LHR')
 await expect(page.getByRole('option',{name:/LHR/})).toBeInViewport()
 await page.getByRole('combobox',{name:'Find an airport'}).press('Enter')
 await page.locator('.association-note').scrollIntoViewIfNeeded()
 await expect(page.locator('.association-note')).toBeInViewport()
 await expect(page.getByRole('button',{name:'Play',exact:true})).toBeInViewport()
 await expect(slider).toBeInViewport()
 const range=await slider.boundingBox(),panel=await page.locator('aside').boundingBox()
 expect(panel!.y+panel!.height).toBeLessThan(range!.y)
 if(viewport.width<=600){const clock=await page.locator('.clock').boundingBox();expect(panel!.y+panel!.height).toBeLessThan(clock!.y)}
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.documentElement.scrollHeight<=innerHeight)).toBe(true)
 await page.screenshot({path:`test-results/${test.info().project.name}-seamless-line.png`,fullPage:true})
})
