import {test,expect} from '@playwright/test'
test('airport search, shared board, selected tracks, phone layout and fast streaming',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('./');await expect(page.getByRole('button',{name:'Play',exact:true})).toBeEnabled()
 await expect(page.locator('.count')).toContainText('aircraft')
 await page.getByRole('combobox',{name:'Find an airport'}).fill('Heathrow');await page.getByRole('combobox',{name:'Find an airport'}).press('Enter')
 await expect(page.locator('.ms-airport-hero')).toContainText('Heathrow')
 await expect(page.locator('.count')).toContainText('inbound');await expect(page.locator('.airport-key')).toContainText('Outbound')
 const rows=page.locator('.ms-split-flap-board__select');await expect(rows.first()).toBeVisible();await rows.first().click();await expect(page.locator('.flight-caption')).toBeVisible()
 await page.getByRole('button',{name:'Arrivals',exact:false}).click()
 await expect(page.locator('.ms-airport-hero')).toContainText('Arrivals')
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.waitForTimeout(1200);await page.screenshot({path:`test-results/${test.info().project.name}-airport.png`,fullPage:true})
 await page.getByRole('button',{name:'Hour density',exact:true}).click();await expect(page.locator('.count')).toContainText('Full study window');await expect(page.locator('.airport-key')).toHaveCount(0);await page.getByRole('button',{name:'Motion',exact:true}).click()
 await page.getByRole('button',{name:'Clear airport'}).click()
 await page.getByRole('slider',{name:'Time of day UTC'}).fill('28500')
 await page.getByRole('combobox',{name:'Playback speed'}).selectOption('900')
 await page.getByRole('button',{name:'Play',exact:true}).click()
 await page.waitForTimeout(5000)
 await expect(page.locator('.initial-loading')).toHaveCount(0)
 await expect.poll(async()=>Number(await page.getByRole('slider').inputValue())).toBeGreaterThan(29500)
 await page.getByRole('button',{name:'Pause',exact:true}).click()
 await page.getByRole('button',{name:'Device details'}).click()
 await expect(page.locator('.diagnostics')).toContainText('/ 4 chunks')
 await page.screenshot({path:`test-results/${test.info().project.name}-europe.png`,fullPage:true})
 expect(errors).toEqual([])
})
test('missing next chunk holds the last frame and offers a working retry',async({page})=>{
 await page.route('**/chunk-043.json.gz.bin',route=>route.fulfill({status:503,body:'unavailable'}))
 await page.goto('./');await expect(page.getByRole('button',{name:'Play',exact:true})).toBeEnabled()
 await page.getByRole('slider').fill('25795');await page.getByRole('combobox',{name:'Playback speed'}).selectOption('900');await page.getByRole('button',{name:'Play',exact:true}).click()
 await expect(page.locator('.stream-status')).toContainText('Retry');expect(Number(await page.getByRole('slider').inputValue())).toBeLessThan(25800)
 await expect(page.locator('.initial-loading')).toHaveCount(0)
 await page.unroute('**/chunk-043.json.gz.bin');await page.getByRole('button',{name:'Retry',exact:true}).click();await expect(page.locator('.stream-status')).toContainText('Paused')
 expect(Number(await page.getByRole('slider').inputValue())).toBeGreaterThanOrEqual(25800)
})
