import {aircraftText} from './release-expectations'
import {pauseAtStart} from './playback-helpers'
import {test,expect,type Page} from '@playwright/test'
const add=async(page:Page,query:string,name:RegExp)=>{const search=page.getByRole('combobox',{name:'Search flights'});await search.fill(query);await page.getByRole('option',{name}).click()}
const ready=async(page:Page)=>{await page.goto('./');await pauseAtStart(page)}

test('unified pills combine airlines, airports and routes across map, activity and boards',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await ready(page)
 const allActivity=await page.locator('.ms-study-timeline svg').innerHTML()
 await add(page,'swiss',/^SWISS/)
 await expect(page.locator('.selection-summary')).toContainText(aircraftText({airlines:['swiss']}))
 await expect(page.locator('.count')).toContainText('SWISS')
 expect(await page.locator('.ms-study-timeline svg').innerHTML()).not.toEqual(allActivity)
 await add(page,'easyjet',/^easyJet/)
 await expect(page.getByRole('group',{name:'Selected filters'})).toContainText('SWISS')
 await expect(page.getByRole('group',{name:'Selected filters'})).toContainText('easyJet')
 await expect(page.locator('.selection-summary')).toContainText(aircraftText({airlines:['swiss','easyjet']}))
 await add(page,'ZRH',/^ZRH Zurich/)
 await expect(page.locator('.ms-airport-hero')).toHaveCount(0)
 await expect(page.locator('.airport-key')).toContainText('inbound')
 await page.getByRole('button',{name:'ZRH board'}).click()
 await expect(page.locator('.ms-airport-hero')).toContainText('ZRH')
 await expect(page.locator('.ms-split-flap-board__select').first()).toBeVisible()
 await page.locator('.ms-split-flap-board__select').first().click()
 await expect(page.locator('.flight-caption')).toBeVisible()
 await page.getByRole('button',{name:'Close airport board'}).click()
 await add(page,'LHR',/^LHR London/)
 await expect(page.getByRole('button',{name:'LHR board'})).toBeVisible()
 await page.getByRole('button',{name:'Remove easyJet'}).click()
 await add(page,'LHR ZRH',/^LHR ↔ ZRH/)
 await expect(page.locator('.ms-study-timeline__heading')).toContainText('LHR ↔ ZRH')
 await expect(page.locator('.selection-summary')).not.toContainText('0 aircraft')
 await page.getByRole('button',{name:'View settings',exact:true}).click()
 await page.getByRole('button',{name:'Hour density',exact:true}).click()
 await expect(page.locator('.count')).toContainText('5-minute snapshots')
 await page.getByRole('button',{name:'Motion',exact:true}).click()
 await page.getByRole('button',{name:'Close view settings'}).click()
 await page.screenshot({path:`test-results/${test.info().project.name}-multi-selection.png`,fullPage:true})
 await page.getByRole('button',{name:'Clear all',exact:true}).click()
 await expect(page.getByRole('group',{name:'Selected filters'})).toHaveCount(0)
 expect(await page.locator('.ms-study-timeline svg').innerHTML()).toEqual(allActivity)
 expect(errors).toEqual([])
})

test('search keyboard, empty intersections, removal and many pills keep the controls usable',async({page})=>{
 await ready(page)
 const search=page.getByRole('combobox',{name:'Search flights'})
 await search.fill('Heathrow');await search.press('Enter')
 await expect(page.getByRole('button',{name:'Remove LHR'})).toBeVisible()
 await add(page,'easyjet',/^easyJet/)
 await expect(page.locator('.selection-summary')).toContainText('0 aircraft')
 await expect(page.locator('.count')).toHaveText(/^0 aircraft/)
 await page.getByRole('button',{name:'Remove LHR'}).click()
 await expect(page.locator('.selection-summary')).toContainText(aircraftText({airlines:['easyjet']}))
 for(const [query,name] of [['swiss',/^SWISS/],['ryanair',/^Ryanair/],['lufthansa',/^Lufthansa/],['british',/^British Airways/]] as const)await add(page,query,name)
 await expect(page.locator('.filter-pill')).toHaveCount(5)
 await expect(page.locator('.play')).toBeInViewport()
 await search.fill('zzzzzzzz');await expect(page.locator('.search-empty')).toBeVisible()
 await search.press('Escape');await expect(page.getByRole('listbox')).toHaveCount(0)
 await search.fill('United');await page.getByRole('option',{name:/^United Airlines/}).click()
 await expect(page.getByRole('button',{name:'Remove United'})).toBeVisible()
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.documentElement.scrollHeight<=innerHeight)).toBe(true)
})

test('compact phone layout reserves map space and boards scroll clear of the timeline',async({page})=>{
 await page.setViewportSize({width:390,height:664})
 await ready(page);await add(page,'SWISS',/^SWISS/)
 const viewport=page.viewportSize()!,panel=await page.locator('aside').boundingBox(),footer=await page.locator('footer').boundingBox()
 if(viewport.width<700){
  const selection=await page.locator('.selection-tools').boundingBox(),insights=await page.locator('.insights-panel').boundingBox()
  expect(selection!.height).toBeLessThan(145)
  expect(insights!.height).toBeLessThan(50)
  // The new collapsed Insights control occupies one additional touch row.
  expect(footer!.y-panel!.y-panel!.height).toBeGreaterThan(viewport.height*.4-insights!.height-8)
 }
 await expect(page.getByRole('combobox',{name:'Aircraft renderer'})).toHaveCount(0)
 await page.screenshot({path:`test-results/${test.info().project.name}-compact-swiss.png`,fullPage:true})
 await add(page,'ZRH',/^ZRH Zurich/);await page.getByRole('button',{name:'ZRH board'}).click()
 await page.locator('.association-note').scrollIntoViewIfNeeded();await expect(page.locator('.association-note')).toBeInViewport()
 const board=await page.locator('.airport-panel').boundingBox(),slider=await page.getByRole('slider',{name:'Time of day UTC'}).boundingBox()
 expect(board!.y+board!.height).toBeLessThan(slider!.y)
 await expect(page.locator('.play')).toBeInViewport()
 await page.getByRole('button',{name:'Close airport board'}).click()
 await page.getByRole('button',{name:'View settings',exact:true}).click()
 await page.getByRole('button',{name:'Show activity as a line'}).click()
 await page.getByRole('button',{name:'Close view settings'}).click()
 await expect(page.locator('.ms-study-timeline svg polyline').first()).toBeVisible()
 await page.getByRole('slider',{name:'Time of day UTC'}).press('Home');await expect(page.getByRole('slider',{name:'Time of day UTC'})).toHaveValue('0')
 await page.getByRole('slider',{name:'Time of day UTC'}).fill('43200');await expect(page.getByRole('slider',{name:'Time of day UTC'})).toHaveValue('43200')
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.documentElement.scrollHeight<=innerHeight)).toBe(true)
})

test('missing next chunk holds the last frame and offers a working retry',async({page})=>{
 await page.route('**/chunk-043.json.gz.bin',route=>route.fulfill({status:503,body:'unavailable'}))
 await ready(page)
 await page.getByRole('slider',{name:'Time of day UTC'}).fill('25795');await page.getByRole('combobox',{name:'Playback speed'}).selectOption('900');await page.locator('.play').click()
 await expect(page.locator('.stream-status')).toContainText('Retry')
 // The one-second slider rounds 07:09:59.5 up; the map clock still reflects the held frame.
 await expect(page.locator('.clock')).toContainText('07:09')
 expect(Number(await page.getByRole('slider',{name:'Time of day UTC'}).inputValue())).toBeLessThanOrEqual(25800)
 await expect(page.locator('.initial-loading')).toHaveCount(0)
 await page.unroute('**/chunk-043.json.gz.bin');await page.getByRole('button',{name:'Retry',exact:true}).click();await expect(page.locator('.stream-status')).toContainText('Paused')
 expect(Number(await page.getByRole('slider',{name:'Time of day UTC'}).inputValue())).toBeGreaterThanOrEqual(25800)
})

test('fast streaming and midnight loops preserve multiple filters',async({page})=>{
 await ready(page);await add(page,'swiss',/^SWISS/);await add(page,'easyJet',/^easyJet/)
 await page.getByRole('combobox',{name:'Playback speed'}).selectOption('900')
 await page.getByRole('slider',{name:'Time of day UTC'}).fill('28500');await page.locator('.play').click()
 await expect.poll(async()=>Number(await page.getByRole('slider',{name:'Time of day UTC'}).inputValue())).toBeGreaterThan(29500)
 await expect(page.locator('.initial-loading')).toHaveCount(0);await page.locator('.play').click()
 for(const speed of ['60','900']){
  await page.getByRole('combobox',{name:'Playback speed'}).selectOption(speed)
  await page.getByRole('slider',{name:'Time of day UTC'}).fill('86399');await expect(page.locator('.stream-status')).toHaveText('Paused')
  await expect(page.getByRole('slider',{name:'Time of day UTC'})).toHaveValue('86399');await page.locator('.play').click()
  await expect.poll(async()=>Number(await page.getByRole('slider',{name:'Time of day UTC'}).inputValue())).toBeLessThan(600)
  await expect(page.locator('.play')).toHaveText('Pause');await page.locator('.play').click()
  await expect(page.locator('.filter-pill')).toHaveCount(2)
 }
})


test('short phone viewport keeps search, playback and touch targets clear',async({page})=>{
 await page.setViewportSize({width:375,height:600})
 await ready(page);await add(page,'SWISS',/^SWISS/)
 const search=await page.locator('aside').boundingBox(),footer=await page.locator('footer').boundingBox()
 expect(footer!.y-search!.y-search!.height).toBeGreaterThan(140)
 for(const locator of [page.locator('.play'),page.getByRole('button',{name:'View settings',exact:true}),page.getByRole('button',{name:'Zoom in'}),page.getByRole('button',{name:'Remove SWISS'})]){
  const box=await locator.boundingBox();expect(Math.round(box!.height*1000)/1000).toBeGreaterThanOrEqual(44)
 }
 const details=await page.getByRole('button',{name:'Device details'}).boundingBox(),about=await page.locator('.method summary').boundingBox()
 expect(about!.x-details!.x-details!.width).toBeGreaterThanOrEqual(8)
 await page.getByRole('combobox',{name:'Search flights'}).fill('LHR ZRH')
 await expect(page.getByRole('option',{name:/^LHR ↔ ZRH/})).toBeInViewport()
 await page.getByRole('option',{name:/^LHR ↔ ZRH/}).click()
 await expect(page.getByRole('button',{name:'Remove LHR ↔ ZRH'})).toBeVisible()
 await page.screenshot({path:`test-results/${test.info().project.name}-short-phone.png`,fullPage:true})
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.documentElement.scrollHeight<=innerHeight)).toBe(true)
})

test('search results resize above the phone keyboard viewport',async({page})=>{
 await page.setViewportSize({width:390,height:664});await ready(page)
 await page.getByRole('combobox',{name:'Search flights'}).fill('London')
 await page.evaluate(()=>{Object.defineProperty(visualViewport!,'height',{value:330,configurable:true});visualViewport!.dispatchEvent(new Event('resize'))})
 const results=await page.locator('.search-popover').boundingBox()
 expect(results!.y+results!.height).toBeLessThanOrEqual(318)
 await page.getByRole('option',{name:/^LHR London/}).click()
 await expect(page.getByRole('button',{name:'Remove LHR'})).toBeVisible()
 await expect(page.getByRole('listbox')).toHaveCount(0)
})

test('laptop transport stays shallow with readable controls and a usable scrub target',async({page})=>{
 await page.setViewportSize({width:1366,height:700});await ready(page)
 const footer=await page.locator('footer').boundingBox(),slider=await page.getByRole('slider',{name:'Time of day UTC'}).boundingBox()
 expect(footer!.height).toBeLessThan(145);expect(slider!.height).toBeGreaterThanOrEqual(44)
 for(const control of [page.locator('.play'),page.getByRole('combobox',{name:'Playback speed'}),page.getByRole('button',{name:'View settings',exact:true})]){
  const box=await control.boundingBox();expect(box!.height).toBeGreaterThanOrEqual(44)
  expect(box!.y).toBeLessThan(slider!.y+slider!.height)
  expect(box!.y+box!.height).toBeGreaterThan(slider!.y)
 }
 await page.getByRole('button',{name:'View settings',exact:true}).click()
 const panel=await page.locator('.view-settings').boundingBox();expect(panel!.y+panel!.height).toBeLessThan(footer!.y)
 await page.getByRole('button',{name:'Close view settings'}).click()
 await page.getByRole('slider',{name:'Time of day UTC'}).fill('43200');await expect(page.getByRole('slider',{name:'Time of day UTC'})).toHaveValue('43200')
 await page.screenshot({path:`test-results/${test.info().project.name}-laptop.png`,fullPage:true})
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.documentElement.scrollHeight<=innerHeight)).toBe(true)
})
