import {test,expect} from '@playwright/test'
import {pauseAtStart} from './playback-helpers'
for(const renderer of ['canvas','three'])test(`${renderer}: watch mode hides the interface, idles and restores playback settings`,async({page})=>{
 // Exercise the unobstructed fallback independently of host fullscreen support.
 await page.addInitScript(()=>{HTMLElement.prototype.requestFullscreen=()=>Promise.reject(new Error('Unavailable'))})
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto(`./?renderer=${renderer}`);await pauseAtStart(page)
 if(renderer==='three')await expect(page.locator('.gpu-layer')).toBeVisible()
 await page.getByLabel('Playback speed').selectOption('900')
 const study=page.locator('.study'),entry=page.getByRole('button',{name:'Enter watch mode'})
 await entry.click();await expect(study).toHaveAttribute('data-watch','true')
 for(const selector of ['header','footer','.workspace>aside','.airport-labels','.map-caption','.view-controls'])await expect(study.locator(selector)).toBeHidden()
 await expect(page.locator('.play')).toHaveText('Pause')
 await expect(page.getByLabel('Playback speed')).toHaveValue('60')
 await expect.poll(()=>page.locator('.ms-timeline-scrubber input').inputValue()).not.toBe('25200')
 await expect(study).not.toHaveAttribute('data-watch-awake','true',{timeout:7000})
 await expect(page.locator('.watch-exit')).toHaveCSS('opacity','0')
 await page.mouse.move(80,100);await expect(study).toHaveAttribute('data-watch-awake','true')
 await page.keyboard.press('Escape')
 await expect(study).not.toHaveAttribute('data-watch','true')
 await expect(entry).toBeFocused();await expect(page.locator('.play')).toHaveText('Play')
 await expect(page.getByLabel('Playback speed')).toHaveValue('900')
 await expect(study.locator('footer')).toBeVisible()
 expect(errors).toEqual([])
})
test('watch mode exits via touch and restores density and the existing filter',async({page})=>{
 await page.addInitScript(()=>{HTMLElement.prototype.requestFullscreen=()=>Promise.reject(new Error('Unavailable'))})
 await page.goto('./#airports=EGLL');await pauseAtStart(page)
 await expect(page.getByRole('button',{name:'Remove LHR',exact:true})).toBeVisible()
 const hash=new URL(page.url()).hash
 await page.getByRole('button',{name:'View settings',exact:true}).click()
 await page.getByRole('button',{name:'Hour density',exact:true}).click()
 await page.getByRole('button',{name:'Close view settings'}).click()
 await page.getByRole('button',{name:'Enter watch mode'}).click()
 await expect(page.locator('.study')).toHaveAttribute('data-watch','true')
 await expect(page.locator('.study')).not.toHaveAttribute('data-watch-awake','true',{timeout:7000})
 await page.locator('.stage>canvas').first().dispatchEvent('pointerdown',{pointerId:1,pointerType:'touch',clientX:50,clientY:50})
 await page.locator('.stage>canvas').first().dispatchEvent('pointerup',{pointerId:1,pointerType:'touch',clientX:50,clientY:50})
 await page.getByRole('button',{name:'Exit watch mode'}).click()
 await expect(page.locator('.play')).toBeDisabled()
 expect(new URL(page.url()).hash).toBe(hash)
 await expect(page.locator('.flight-caption')).toHaveCount(0)
})
test('native fullscreen exit restores the normal interface',async({page,browserName})=>{
 test.skip(browserName!=='chromium','Native fullscreen is tested on desktop Chromium')
 await page.goto('./');await pauseAtStart(page)
 await page.getByRole('button',{name:'Enter watch mode'}).click()
 await expect.poll(()=>page.evaluate(()=>document.fullscreenElement?.className)).toBe('study')
 await page.evaluate(()=>document.exitFullscreen())
 await expect(page.locator('.study')).not.toHaveAttribute('data-watch','true')
 await expect(page.getByRole('button',{name:'Enter watch mode'})).toBeFocused()
})
